version: "3"
name: abusedb

services:
  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - ./data:/data
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_ROOT_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INIT_ROOT_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_INIT_ROOT_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: "glandix"
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    depends_on:
      - mongo

networks:
  public:
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
